### ISSUE TITLE
Some question about the source code

### ISSUE THREAD

**Issue by anwerso** [artem328/clampify#2]
https://github.com/artem328/clampify/blob/master/clampify.js#L383

Is there any significance of a second parameter? `_addEndsWithNodeToEnd` have arity of 1 if i understand correctly.

**Comment by artem328** [comment]
I believe I just forgot to remove the second parameter on `_addEndsWithNodeToEnd` call when changed the method. So there is no sense to pass second argument. Thanks for notice
